how do you evaluate the performance of your model when you are trying to predict a continuous variable? Why?

when we predict a continuous variable we have to evaluate the performance of our model with RMSE. Why? we have to know differnce between predicted outcome and actual outcome. RMSE should be small as much as posibile it means our model works well.

Take a numpy array [1,2,3,4,5,6] and multiply each value in that array by 3 as simply as possible.

In [4]:
import numpy as np
np_array = [1,2,3,4,5,6] 
out_num = np.multiply(np_array, 3) 
out_num

array([ 3,  6,  9, 12, 15, 18])

1. Look up the Adam optimization functions in PyTorch
https://pytorch.org/docs/stable/optim.html . How does it work? Try at least one other
optimization function with the diabetes dataset shown in class. How does the model
perform with the new optimizer? Did it perform better or worse than Adam? Why do you
think that is?

In [106]:
import pandas as pd
import torch
diabetes_df = pd.read_csv('diabetes.csv')
diabetes_df.head()


Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

In [107]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

X = diabetes_df.drop('Outcome',axis=1).values
y = diabetes_df['Outcome'].values

# Split into training and test set
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size = 0.3, random_state=42,stratify=y)

# Standardize
sc = StandardScaler()
X_train=sc.fit_transform(X_train)
X_test=sc.fit_transform(X_test)
print(X_train)
print(X_test)
print(y_train)

[[ 0.93138344  2.0179454   0.78066953 ...  0.43148259 -0.37477883
   0.63212912]
 [ 0.63260632 -1.14861888  0.46538785 ... -0.1198324  -0.29416766
   0.71699246]
 [-0.56250219 -0.47692343 -0.2702694  ... -0.20958135  2.74517192
   0.03808578]
 ...
 [-0.86127931 -0.76479291  0.04501228 ...  0.76483585 -0.78380586
  -0.30136756]
 [ 0.63260632  2.20985838  1.2010451  ...  0.43148259 -0.60466993
   2.75371249]
 [ 0.03505207  0.73852549 -0.58555107 ... -0.33779414 -0.57779954
   0.29267578]]
[[-0.221984    0.27295557  0.44799643 ... -0.40520351 -0.40095552
   0.12710397]
 [ 0.07103488 -0.35398926 -0.25023029 ...  0.38971803  1.41135157
  -0.55970343]
 [ 2.12216705  0.66106428  1.24596982 ...  0.61328971 -0.61581667
   1.58656968]
 ...
 [ 2.70820481 -0.44355281  0.1487564  ...  0.61328971 -0.85247533
   1.07146414]
 [-0.51500288  1.10888202  1.04647647 ... -0.00774274  1.0999586
   2.87433355]
 [-0.80802176 -0.17486217  0.04900973 ...  0.36487673  0.240514
  -0.04459788]]
[1 0 0 0 0 1 0 0 0 

In [108]:
import torch.nn as nn
import torch.nn.functional as F # where the activation functions are 
# create tensors = matrices 
X_train = torch.FloatTensor(X_train)
print(X_train)
X_test = torch.FloatTensor(X_test)
print(X_test)

tensor([[ 0.9314,  2.0179,  0.7807,  ...,  0.4315, -0.3748,  0.6321],
        [ 0.6326, -1.1486,  0.4654,  ..., -0.1198, -0.2942,  0.7170],
        [-0.5625, -0.4769, -0.2703,  ..., -0.2096,  2.7452,  0.0381],
        ...,
        [-0.8613, -0.7648,  0.0450,  ...,  0.7648, -0.7838, -0.3014],
        [ 0.6326,  2.2099,  1.2010,  ...,  0.4315, -0.6047,  2.7537],
        [ 0.0351,  0.7385, -0.5856,  ..., -0.3378, -0.5778,  0.2927]])
tensor([[-0.2220,  0.2730,  0.4480,  ..., -0.4052, -0.4010,  0.1271],
        [ 0.0710, -0.3540, -0.2502,  ...,  0.3897,  1.4114, -0.5597],
        [ 2.1222,  0.6611,  1.2460,  ...,  0.6133, -0.6158,  1.5866],
        ...,
        [ 2.7082, -0.4436,  0.1488,  ...,  0.6133, -0.8525,  1.0715],
        [-0.5150,  1.1089,  1.0465,  ..., -0.0077,  1.1000,  2.8743],
        [-0.8080, -0.1749,  0.0490,  ...,  0.3649,  0.2405, -0.0446]])


In [109]:
y_train = torch.LongTensor(y_train)
print(y_train)
y_test = torch.LongTensor(y_test)
print(y_test)

tensor([1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
        0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0,
        0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1,
        0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0,
        1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1,
        1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0,
        0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0,
        1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0,
        0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0,
        1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0,

In [110]:
#artificial neural network
class ANN_model(nn.Module):
    def __init__(self,input_features=8,hidden1=20,hidden2=20,out_features=2):
        super().__init__()# super is a computed indirect reference. so, it isolates changes
        # and make sure that children in the layers of multiple inheritence are calling
        # the right parents
        self.layer_1_connection = nn.Linear(input_features,hidden1)
        self.layer_2_connection = nn.Linear(hidden1,hidden2)
        self.out = nn.Linear(hidden2,out_features)
     
    def forward(self,x):
        #apply activation functions
        x = F.relu(self.layer_1_connection(x))
        x = F.relu(self.layer_2_connection(x))
        x = self.out(x)
        return x

In [111]:
torch.manual_seed(42)
# create instance of model
ann = ANN_model()

In [132]:
# loss function
loss_function = nn.CrossEntropyLoss()

#optimizer
optimizer = torch.optim.Adamax(ann.parameters(),lr=0.60) #  learning rate-
                                                    #How fast does it go to learn? There are reasons why you wouldn't want it to learn too quickly 'cause it can make hasty generalizations. You know two slowly is going to take forever, and that's also not good.


In [133]:
# run model through multiple epochs/iterations
final_loss = []
n_epochs = 500
for epoch in range(n_epochs):
    y_pred = ann.forward(X_train)
    loss = loss_function(y_pred,y_train)
    final_loss.append(loss)
    
    if epoch % 10 == 1:
        print(f'Epoch number:{epoch} with loss: {loss}')
        
    optimizer.zero_grad()# zero the gradient  before running backwards propagation
    loss.backward()
    optimizer.step() # perform one optimization step each epoch

Epoch number:1 with loss: 18.410369873046875
Epoch number:11 with loss: 0.8080480694770813
Epoch number:21 with loss: 0.6295515894889832
Epoch number:31 with loss: 0.5494740605354309
Epoch number:41 with loss: 0.4990636110305786
Epoch number:51 with loss: 0.4810987710952759
Epoch number:61 with loss: 0.4678094983100891
Epoch number:71 with loss: 0.4583451747894287
Epoch number:81 with loss: 0.4457942843437195
Epoch number:91 with loss: 0.4404660761356354
Epoch number:101 with loss: 0.43490418791770935
Epoch number:111 with loss: 0.4319230914115906
Epoch number:121 with loss: 0.42929473519325256
Epoch number:131 with loss: 0.42700162529945374
Epoch number:141 with loss: 0.42433279752731323
Epoch number:151 with loss: 0.4255309998989105
Epoch number:161 with loss: 0.4186752438545227
Epoch number:171 with loss: 0.4129730463027954
Epoch number:181 with loss: 0.40999913215637207
Epoch number:191 with loss: 0.40814119577407837
Epoch number:201 with loss: 0.40647464990615845
Epoch number:211 

In [134]:
# predictions
y_pred = []

with torch.no_grad():
    for i, data in enumerate(X_test):
        prediction = ann(data)
        y_pred.append(prediction.argmax())
y_pred        

[tensor(1),
 tensor(1),
 tensor(1),
 tensor(1),
 tensor(1),
 tensor(1),
 tensor(1),
 tensor(1),
 tensor(0),
 tensor(0),
 tensor(0),
 tensor(0),
 tensor(1),
 tensor(1),
 tensor(1),
 tensor(1),
 tensor(1),
 tensor(1),
 tensor(1),
 tensor(0),
 tensor(1),
 tensor(1),
 tensor(0),
 tensor(0),
 tensor(1),
 tensor(0),
 tensor(1),
 tensor(1),
 tensor(0),
 tensor(0),
 tensor(1),
 tensor(1),
 tensor(1),
 tensor(0),
 tensor(0),
 tensor(1),
 tensor(0),
 tensor(1),
 tensor(0),
 tensor(1),
 tensor(0),
 tensor(1),
 tensor(0),
 tensor(0),
 tensor(0),
 tensor(1),
 tensor(1),
 tensor(0),
 tensor(0),
 tensor(0),
 tensor(0),
 tensor(0),
 tensor(1),
 tensor(0),
 tensor(1),
 tensor(0),
 tensor(1),
 tensor(1),
 tensor(1),
 tensor(0),
 tensor(0),
 tensor(0),
 tensor(1),
 tensor(1),
 tensor(0),
 tensor(0),
 tensor(1),
 tensor(0),
 tensor(1),
 tensor(0),
 tensor(1),
 tensor(1),
 tensor(0),
 tensor(0),
 tensor(0),
 tensor(1),
 tensor(1),
 tensor(1),
 tensor(0),
 tensor(1),
 tensor(0),
 tensor(0),
 tensor(0),
 ten

In [135]:
from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.89      0.61      0.72       150
           1       0.54      0.86      0.67        81

    accuracy                           0.70       231
   macro avg       0.72      0.74      0.69       231
weighted avg       0.77      0.70      0.70       231



I used Adamax optimizer and changed the learning rate from 0.01 to 0.60. I saw on classification report that recall for class 1 and precision for class 0 increased while recall for class 0 and precision for class 1 decreased if I compare to similar results from Adam optimizer. Recall deltas were higher than Precision deltas. 

Write a function that lists and counts the number of divisors for an input value.
Example 1:
Input: 5
Output: “There are 2 divisors: 1 and 5”
Example 2:
Input: 40
Output: “There are 8 divisors: 1, 2, 4, 5, 8, 10, 20, and 40”

In [59]:
def divisor(n):
    """ this function will find divisor numbers """
    list_num = []   
    for i in range(n):
        if n%(i+1)==0:
            list_num.append(i+1)
    return list_num
                  



print(divisor(15))
print(divisor(40))

[1, 3, 5, 15]
[1, 2, 4, 5, 8, 10, 20, 40]
